from flask_mottak import db

class Leverandor(db.Model):
    kort_lev = db.Column(db.String(6), primary_key=True)
    leverandor = db.Column(db.String(100), unique=True, nullable=False)
    websak = db.Column(db.String(200), unique=False, nullable=True)
    ansv_seksjon = db.Column(db.String(3), nullable=True)
    dataleveranser = db.relationship('Dataleveranse', backref='leverandor',lazy=True)
    # Relasjon som ikke er synlig i basen. Kjøres i bakgrunnen.

    def __repr__(self):
        return f"Leverandor('{self.kort_lev}', '{self.leverandor}', '{self.websak}', '{self.ansv_seksjon}')"


class Dataleveranse(db.Model):
    leveranse = db.Column(db.String(100), primary_key=True)
    kort_lev = db.Column(db.String(6), db.ForeignKey('leverandor.kort_lev'), primary_key=True)
    mot_seksjon = db.Column(db.String(3), nullable=False)
    kontakt_seksjon = db.Column(db.String(120), nullable=False)
    kontaktinfo_seksjon = db.Column(db.String(120), nullable=False)
    kontakt_lev = db.Column(db.String(120), nullable=False)
    kontaktinfo_lev = db.Column(db.String(120), nullable=False)
    forventet_dato_neste = db.Column(db.String(20), nullable=False)
    hyppighet = db.Column(db.String(20), nullable=False)
    dataleverandor = db.relationship('Leverandor', foreign_keys="[Dataleveranse.kort_lev]", backref='leveranse')
    #periodeleveranser = db.relationship('Periodeleveranse', backref='dataleveranse', lazy=True)

    def __repr__(self):
        return f"Dataleveranse('{self.leveranse}', '{self.kort_lev}', '{self.mot_seksjon}', '{self.kontakt_seksjon}')"


class Periodeleveranse(db.Model):
    periode = db.Column(db.String(20), primary_key=True)
    leveranse = db.Column(db.String(100), db.ForeignKey('dataleveranse.leveranse'), primary_key=True)
    kort_lev = db.Column(db.String(6), db.ForeignKey('dataleveranse.kort_lev'), primary_key=True)

    dataleveranse = db.relationship('Dataleveranse',
                    primaryjoin="and_(Periodeleveranse.kort_lev==Dataleveranse.kort_lev," 
                        "Periodeleveranse.leveranse==Dataleveranse.leveranse)", backref='periodeleveranse')

    def __repr__(self):
        return f"Periodeleveranse('{self.periode}', '{self.leveranse}', '{self.kort_lev}')"


class Fil(db.Model):
    periode = db.Column(db.String(20), db.ForeignKey('periodeleveranse.periode'), primary_key=True)
    leveranse = db.Column(db.String(100), db.ForeignKey('periodeleveranse.leveranse'), primary_key=True)
    kort_lev = db.Column(db.String(6), db.ForeignKey('periodeleveranse.kort_lev'), primary_key=True)
    filnavn = db.Column(db.String(200), primary_key=True)
    periodeleveranse = db.relationship('Periodeleveranse',
                                    primaryjoin="and_(Fil.kort_lev==Periodeleveranse.kort_lev,"
                                                "Fil.leveranse==Periodeleveranse.leveranse,"
                                                "Fil.periode==Periodeleveranse.periode)")
    fil_mottatt = db.Column(db.String(20), nullable=False)

    def __init__(self, periode, leveranse, kort_lev, filnavn, fil_mottatt):
        self.periode = periode
        self.leveranse = leveranse
        self.kort_lev = kort_lev
        self.filnavn = filnavn
        self.fil_mottatt = fil_mottatt

    def __repr__(self):
        return f"Fil('{self.periode}', '{self.leveranse}', '{self.kort_lev}', '{self.filnavn}', '{self.fil_mottatt}')"


class Kvalitet(db.Model):
    periode = db.Column(db.String(20), db.ForeignKey('fil.periode'), primary_key=True)
    leveranse = db.Column(db.String(100), db.ForeignKey('fil.leveranse'), primary_key=True)
    kort_lev = db.Column(db.String(6), db.ForeignKey('fil.kort_lev'), primary_key=True)
    filnavn = db.Column(db.String(200), db.ForeignKey('fil.filnavn'), primary_key=True)
    lopenr = db.Column(db.Integer, primary_key=True)
    fil = db.relationship('Fil',
                          primaryjoin="and_(Kvalitet.kort_lev==Fil.kort_lev,"
                                      "Kvalitet.filnavn==Fil.filnavn,"
                                      "Kvalitet.leveranse==Fil.leveranse,"
                                      "Kvalitet.periode==Fil.periode)")
    lenke_rapp = db.Column(db.String(200))
    behandlet_datotid = db.Column(db.String(20), nullable=False)
    antall_obs = db.Column(db.Integer)
    antall_unike_id = db.Column(db.Integer)
    antall_gyldige_id = db.Column(db.Integer)
    antall_gyldige_fnr = db.Column(db.Integer)
    antall_gyldige_dnr = db.Column(db.Integer)
    antall_gyld_fnr_lik = db.Column(db.Integer)
    antall_gyld_fnr_ulik = db.Column(db.Integer)
    antall_gyld_dnr_lik = db.Column(db.Integer)
    antall_gyld_dnr_ulik = db.Column(db.Integer)
    antall_ugyldige = db.Column(db.Integer)
    feil_1e_1 = db.Column(db.Integer)
    feil_1e_2 = db.Column(db.Integer)
    feil_1f_1 = db.Column(db.Integer)
    feil_1f_2 = db.Column(db.Integer)
    feil_2a_1 = db.Column(db.Integer)
    feil_2a_2 = db.Column(db.Integer)
    feil_2a_3 = db.Column(db.Integer)
    feil_2a_4 = db.Column(db.Integer)
    feil_2a_5 = db.Column(db.Integer)
    feil_2a_6 = db.Column(db.Integer)
    feil_2b_1 = db.Column(db.Integer)
    feil_2b_2 = db.Column(db.Integer)
    feil_2b_3 = db.Column(db.Integer)
    feil_2b_4 = db.Column(db.Integer)
    feil_2b_5 = db.Column(db.Integer)
    feil_2b_6 = db.Column(db.Integer)
    feil_2c_1 = db.Column(db.Integer)
    feil_2c_2 = db.Column(db.Integer)
    feil_2d_1 = db.Column(db.Integer)
    feil_2d_2 = db.Column(db.Integer)
    feil_2d_3 = db.Column(db.Integer)
    feil_2e = db.Column(db.Integer)
    feil_2f_1 = db.Column(db.Integer)
    feil_2f_2 = db.Column(db.Integer)
    feil_2f_3 = db.Column(db.Integer)
    feil_2g = db.Column(db.Integer)
    fnr_leting = db.Column(db.String(3))
    t1_antall_id = db.Column(db.Integer)
    t11_ant_koblet_fnr = db.Column(db.Integer)
    t11_ant_feil_a1 = db.Column(db.Integer)
    t11_ant_feil_a2 = db.Column(db.Integer)
    t11_ant_feil_a3 = db.Column(db.Integer)
    t11_ant_feil_a4 = db.Column(db.Integer)
    t11_ant_feil_a5 = db.Column(db.Integer)
    t11_ant_feil_a6 = db.Column(db.Integer)
    t11_ant_feil_b1 = db.Column(db.Integer)
    t11_ant_feil_b2 = db.Column(db.Integer)
    t11_ant_feil_b3 = db.Column(db.Integer)
    t11_ant_feil_b4 = db.Column(db.Integer)
    t11_ant_feil_b5 = db.Column(db.Integer)
    t11_ant_feil_b6 = db.Column(db.Integer)
    t11_ant_feil_c1 = db.Column(db.Integer)
    t11_ant_feil_c2 = db.Column(db.Integer)
    t11_ant_feil_andre = db.Column(db.Integer)
    t11_ant_ikke_kobl = db.Column(db.Integer)
    t12_antall_id = db.Column(db.Integer)
    t12_ant_koblet_dnr = db.Column(db.Integer)
    t12_ant_feil_a1 = db.Column(db.Integer)
    t12_ant_feil_a2 = db.Column(db.Integer)
    t12_ant_feil_a3 = db.Column(db.Integer)
    t12_ant_feil_a4 = db.Column(db.Integer)
    t12_ant_feil_a5 = db.Column(db.Integer)
    t12_ant_feil_a6 = db.Column(db.Integer)
    t12_ant_feil_b1 = db.Column(db.Integer)
    t12_ant_feil_b2 = db.Column(db.Integer)
    t12_ant_feil_b3 = db.Column(db.Integer)
    t12_ant_feil_b4 = db.Column(db.Integer)
    t12_ant_feil_b5 = db.Column(db.Integer)
    t12_ant_feil_b6 = db.Column(db.Integer)
    t12_ant_feil_c1 = db.Column(db.Integer)
    t12_ant_feil_c2 = db.Column(db.Integer)
    t12_ant_feil_andre = db.Column(db.Integer)
    t12_ant_ikke_kobl = db.Column(db.Integer)
    t13_ant_paa_fil = db.Column(db.Integer)
    t13_ant_fnr_koblet = db.Column(db.Integer)
    t13_ant_dnr_koblet = db.Column(db.Integer)
    t13_ant_koblet_fnr_lik = db.Column(db.Integer)
    t13_ant_koblet_fnr_ulik = db.Column(db.Integer)
    t13_ant_koblet_dnr_lik = db.Column(db.Integer)
    t13_ant_koblet_dnr_ulik = db.Column(db.Integer)
    t1_ant_koblet = db.Column(db.Integer)
    t1_ant_ikke_koblet = db.Column(db.Integer)
    t2_antall_id = db.Column(db.Integer)
    t21_ant_koblet_fnr = db.Column(db.Integer)
    t21_ant_feil_a1 = db.Column(db.Integer)
    t21_ant_feil_a2 = db.Column(db.Integer)
    t21_ant_feil_a3 = db.Column(db.Integer)
    t21_ant_feil_a4 = db.Column(db.Integer)
    t21_ant_feil_a5 = db.Column(db.Integer)
    t21_ant_feil_a6 = db.Column(db.Integer)
    t21_ant_feil_b1 = db.Column(db.Integer)
    t21_ant_feil_b2 = db.Column(db.Integer)
    t21_ant_feil_b3 = db.Column(db.Integer)
    t21_ant_feil_b4 = db.Column(db.Integer)
    t21_ant_feil_b5 = db.Column(db.Integer)
    t21_ant_feil_b6 = db.Column(db.Integer)
    t21_ant_feil_c1 = db.Column(db.Integer)
    t21_ant_feil_c2 = db.Column(db.Integer)
    t21_ant_feil_andre = db.Column(db.Integer)
    t21_ant_ikke_kobl = db.Column(db.Integer)
    t22_antall_id = db.Column(db.Integer)
    t22_ant_koblet_dnr = db.Column(db.Integer)
    t22_ant_feil_a1 = db.Column(db.Integer)
    t22_ant_feil_a2 = db.Column(db.Integer)
    t22_ant_feil_a3 = db.Column(db.Integer)
    t22_ant_feil_a4 = db.Column(db.Integer)
    t22_ant_feil_a5 = db.Column(db.Integer)
    t22_ant_feil_a6 = db.Column(db.Integer)
    t22_ant_feil_b1 = db.Column(db.Integer)
    t22_ant_feil_b2 = db.Column(db.Integer)
    t22_ant_feil_b3 = db.Column(db.Integer)
    t22_ant_feil_b4 = db.Column(db.Integer)
    t22_ant_feil_b5 = db.Column(db.Integer)
    t22_ant_feil_b6 = db.Column(db.Integer)
    t22_ant_feil_c1 = db.Column(db.Integer)
    t22_ant_feil_c2 = db.Column(db.Integer)
    t22_ant_feil_andre = db.Column(db.Integer)
    t22_ant_ikke_kobl = db.Column(db.Integer)
    t23_ant_paa_fil = db.Column(db.Integer)
    t23_ant_fnr_koblet = db.Column(db.Integer)
    t23_ant_dnr_koblet = db.Column(db.Integer)
    t23_ant_koblet_fnr_lik = db.Column(db.Integer)
    t23_ant_koblet_fnr_ulik = db.Column(db.Integer)
    t23_ant_koblet_dnr_lik = db.Column(db.Integer)
    t23_ant_koblet_dnr_ulik = db.Column(db.Integer)
    t2_ant_koblet = db.Column(db.Integer)
    t2_ant_ikke_koblet = db.Column(db.Integer)
    t2_ant_avvist = db.Column(db.Integer)
    t3_antall_id = db.Column(db.Integer)
    t31_ant_koblet_fnr = db.Column(db.Integer)
    t31_ant_feil_a1 = db.Column(db.Integer)
    t31_ant_feil_a2 = db.Column(db.Integer)
    t31_ant_feil_a3 = db.Column(db.Integer)
    t31_ant_feil_a4 = db.Column(db.Integer)
    t31_ant_feil_a5 = db.Column(db.Integer)
    t31_ant_feil_a6 = db.Column(db.Integer)
    t31_ant_feil_b1 = db.Column(db.Integer)
    t31_ant_feil_b2 = db.Column(db.Integer)
    t31_ant_feil_b3 = db.Column(db.Integer)
    t31_ant_feil_b4 = db.Column(db.Integer)
    t31_ant_feil_b5 = db.Column(db.Integer)
    t31_ant_feil_b6 = db.Column(db.Integer)
    t31_ant_feil_c1 = db.Column(db.Integer)
    t31_ant_feil_c2 = db.Column(db.Integer)
    t31_ant_feil_andre = db.Column(db.Integer)
    t31_ant_ikke_kobl = db.Column(db.Integer)
    t32_antall_id = db.Column(db.Integer)
    t32_ant_koblet_dnr = db.Column(db.Integer)
    t32_ant_feil_a1 = db.Column(db.Integer)
    t32_ant_feil_a2 = db.Column(db.Integer)
    t32_ant_feil_a3 = db.Column(db.Integer)
    t32_ant_feil_a4 = db.Column(db.Integer)
    t32_ant_feil_a5 = db.Column(db.Integer)
    t32_ant_feil_a6 = db.Column(db.Integer)
    t32_ant_feil_b1 = db.Column(db.Integer)
    t32_ant_feil_b2 = db.Column(db.Integer)
    t32_ant_feil_b3 = db.Column(db.Integer)
    t32_ant_feil_b4 = db.Column(db.Integer)
    t32_ant_feil_b5 = db.Column(db.Integer)
    t32_ant_feil_b6 = db.Column(db.Integer)
    t32_ant_feil_c1 = db.Column(db.Integer)
    t32_ant_feil_c2 = db.Column(db.Integer)
    t32_ant_feil_andre = db.Column(db.Integer)
    t32_ant_ikke_kobl = db.Column(db.Integer)
    t33_ant_paa_fil = db.Column(db.Integer)
    t33_ant_fnr_koblet = db.Column(db.Integer)
    t33_ant_dnr_koblet = db.Column(db.Integer)
    t33_ant_koblet_fnr_lik = db.Column(db.Integer)
    t33_ant_koblet_fnr_ulik = db.Column(db.Integer)
    t33_ant_koblet_dnr_lik = db.Column(db.Integer)
    t33_ant_koblet_dnr_ulik = db.Column(db.Integer)
    t3_ant_koblet = db.Column(db.Integer)
    t3_ant_ikke_koblet = db.Column(db.Integer)
    t4_antall_id = db.Column(db.Integer)
    t41_ant_koblet = db.Column(db.Integer)
    t41_ant_feil_a1 = db.Column(db.Integer)
    t41_ant_feil_a2 = db.Column(db.Integer)
    t41_ant_feil_a3 = db.Column(db.Integer)
    t41_ant_feil_a4 = db.Column(db.Integer)
    t41_ant_feil_a5 = db.Column(db.Integer)
    t41_ant_feil_a6 = db.Column(db.Integer)
    t41_ant_feil_b1 = db.Column(db.Integer)
    t41_ant_feil_b2 = db.Column(db.Integer)
    t41_ant_feil_b3 = db.Column(db.Integer)
    t41_ant_feil_b4 = db.Column(db.Integer)
    t41_ant_feil_b5 = db.Column(db.Integer)
    t41_ant_feil_b6 = db.Column(db.Integer)
    t41_ant_feil_c1 = db.Column(db.Integer)
    t41_ant_feil_c2 = db.Column(db.Integer)
    t41_ant_feil_e = db.Column(db.Integer)
    t41_ant_feil_f1 = db.Column(db.Integer)
    t41_ant_feil_f2 = db.Column(db.Integer)
    t41_ant_feil_f3 = db.Column(db.Integer)
    t41_ant_feil_andre = db.Column(db.Integer)
    t41_ant_ikke_kobl = db.Column(db.Integer)
    t43_ant_paa_fil = db.Column(db.Integer)
    t43_ant_fnr_koblet = db.Column(db.Integer)
    t43_ant_dnr_koblet = db.Column(db.Integer)
    t43_ant_koblet_fnr_lik = db.Column(db.Integer)
    t43_ant_koblet_fnr_ulik = db.Column(db.Integer)
    t43_ant_koblet_dnr_lik = db.Column(db.Integer)
    t43_ant_koblet_dnr_ulik = db.Column(db.Integer)
    t4_ant_koblet = db.Column(db.Integer)
    t4_ant_ikke_koblet = db.Column(db.Integer)
    t5_antall_id = db.Column(db.Integer)
    t51_ant_koblet = db.Column(db.Integer)
    t51_ant_feil_a1 = db.Column(db.Integer)
    t51_ant_feil_a2 = db.Column(db.Integer)
    t51_ant_feil_a3 = db.Column(db.Integer)
    t51_ant_feil_a4 = db.Column(db.Integer)
    t51_ant_feil_a5 = db.Column(db.Integer)
    t51_ant_feil_a6 = db.Column(db.Integer)
    t51_ant_feil_b1 = db.Column(db.Integer)
    t51_ant_feil_b2 = db.Column(db.Integer)
    t51_ant_feil_b3 = db.Column(db.Integer)
    t51_ant_feil_b4 = db.Column(db.Integer)
    t51_ant_feil_b5 = db.Column(db.Integer)
    t51_ant_feil_b6 = db.Column(db.Integer)
    t51_ant_feil_c1 = db.Column(db.Integer)
    t51_ant_feil_c2 = db.Column(db.Integer)
    t51_ant_feil_e = db.Column(db.Integer)
    t51_ant_feil_f1 = db.Column(db.Integer)
    t51_ant_feil_f2 = db.Column(db.Integer)
    t51_ant_feil_f3 = db.Column(db.Integer)
    t51_ant_feil_andre = db.Column(db.Integer)
    t51_ant_ikke_kobl = db.Column(db.Integer)
    t53_ant_paa_fil = db.Column(db.Integer)
    t53_ant_fnr_koblet = db.Column(db.Integer)
    t53_ant_dnr_koblet = db.Column(db.Integer)
    t53_ant_koblet_fnr_lik = db.Column(db.Integer)
    t53_ant_koblet_fnr_ulik = db.Column(db.Integer)
    t53_ant_koblet_dnr_lik = db.Column(db.Integer)
    t53_ant_koblet_dnr_ulik = db.Column(db.Integer)
    t5_ant_koblet = db.Column(db.Integer)
    t5_ant_ikke_koblet = db.Column(db.Integer)

    #def __repr__(self):
    #    return f"Kvalitet('{self.periode}', '{self.leveranse}', '{self.kort_lev}', '{self.filnavn}', '{self.fil_mottatt}'," \
    #           f"'{self.periode }','{self.leveranse}', '{self.kort_lev}', '{self.filnavn}', '{self.lopenr}', '{self.lenke_rapp}', " \
    #           f"'{self.behandlet_datotid}', '{self.antall_obs}', '{self.antall_unike_id }','{self.antall_gyldige_id }'," \
    #           f"'{self.antall_gyldige_fnr }', '{self.antall_gyldige_dnr }', '{self.antall_gyld_fnr_lik }', '{self.antall_gyld_fnr_ulik }'," \
    #           f"'{self.antall_gyld_dnr_lik }', '{self.antall_gyld_dnr_ulik }', '{self.antall_ugyldige }')"



